cosapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('product/new/', views.product_new, name='product_new'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('product/<int:pk>/purchase/', views.purchase_new, name='purchase_new'),
    path('product/<int:pk>/review/', views.review_new, name='review_new'),
    path('', views.product_list, name='home'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('user/<str:username>', views.user_purchase, name='user_purchase'),
    path('user/<str:username>/reviews', views.user_review, name='user_review'),
    path('category/<int:pk>', views.category_view, name='category'),
    path('brand/<int:pk>', views.brand_view, name='brand'),
    path('search/', views.search_view, name='search'),
]

cosproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cosapp.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cosapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Brand(models.Model):
    title = models.CharField(max_length=30)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=30)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField('название', max_length=50)
    brand = models.ForeignKey(Brand, verbose_name='бренд', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='категория', on_delete=models.CASCADE)
    picture = models.ImageField('изображение', upload_to='products')

    def __str__(self):
        return self.title

    def get_average_rating(self):
        reviews = Review.objects.filter(product=self)
        if reviews.exists():
            return reviews.aggregate(models.Avg('rating'))['rating__avg']
        return 0

    def get_minimal_price(self):
        purchases = Purchase.objects.filter(product=self)
        if purchases.exists():
            return purchases.aggregate(models.Min('price'))['price__min']
        return 0

    def get_hearts_display(self):
        avg = self.get_average_rating()
        import math
        hearts_rating = math.ceil(avg)
        if hearts_rating == 1:
            return '💔'
        elif hearts_rating == 2:
            return '💛💛'
        elif hearts_rating == 3:
            return '🧡🧡🧡'
        elif hearts_rating == 4:
            return '🩷🩷🩷🩷'
        elif hearts_rating == 5:
            return '❤️❤️❤️❤️❤️'
        else:
            return ''


class Purchase(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField('стоимость', max_digits=6, decimal_places=2)
    date = models.DateField('дата', null=True)
    store = models.CharField('магазин', max_length=30)

    def __str__(self):
        return f'{self.user.username} - {self.product.title}'


RATING_CHOICES = [
    (1, '💔'),
    (2, '💛💛'),
    (3, '🧡🧡🧡'),
    (4, '🩷🩷🩷🩷'),
    (5, '❤️❤️❤️❤️❤️️'),
]


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField('рейтинг', choices=RATING_CHOICES)
    comment = models.TextField('комментарий')
    liked = models.BooleanField('понравилось ?', null=True)

    def __str__(self):
        return f'{self.user.username} - {self.product.title}'

cosapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.text import capfirst

from .models import Product, Purchase, Review


class LoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=255, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class PurchaseForm(forms.ModelForm):
    date = forms.DateField(
        label=capfirst(Purchase.date.field.verbose_name), required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    store = forms.CharField(label=capfirst(Purchase.store.field.verbose_name), required=False)

    class Meta:
        model = Purchase
        exclude = ('user', 'product')


class ReviewForm(forms.ModelForm):
    comment = forms.CharField(label=capfirst(Review.comment.field.verbose_name), widget=forms.Textarea, required=False)

    class Meta:
        model = Review
        exclude = ('user', 'product')

cosapp/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import (
    Avg,
    Min,
    Q
)
from django.shortcuts import render, redirect
from .forms import LoginForm, SignUpForm, ProductForm, PurchaseForm, ReviewForm
from .models import Product, Purchase, Review, Category, Brand


# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    context = {'form': form}
    return render(request, 'signup.html', context)


def logout_view(request):
    logout(request)
    return redirect('home')


def product_new(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            return redirect('product_detail', pk=product.pk)
    else:
        form = ProductForm()
    context = {'form': form}
    return render(request, 'product_edit.html', context)


def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    purchase_form = PurchaseForm()
    review_form = ReviewForm()
    reviews = Review.objects.filter(product=product)
    purchases = Purchase.objects.filter(product=product)
    avg_rating = product.get_average_rating()
    context = {'product': product, 'purchase_form':  purchase_form, 'review_form':  review_form, 'reviews': reviews,
               'avg_rating': avg_rating, 'purchases': purchases}
    return render(request, 'product_detail.html', context)


def purchase_new(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':
        form = PurchaseForm(request.POST)
        if form.is_valid():
            purchase = form.save(commit=False)
            purchase.user = request.user
            purchase.product = product
            purchase.save()
            return redirect('product_detail', pk=pk)
    return redirect('product_detail', pk=pk)


def review_new(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.product = product
            review.save()
            return redirect('product_detail', pk=pk)
    return redirect('product_detail', pk=pk)


def product_list(request):
    products = Product.objects.annotate(avg_rating=Avg('review__rating')).order_by("brand__title", "title")
    paginator = Paginator(products, 16)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'product_list.html', context)


def user_purchase(request, username):
    profile = User.objects.get(username=username)
    purchases = Purchase.objects.filter(user=profile)
    context = {'profile': profile, 'purchases': purchases}
    return render(request, 'user_purchase.html', context)


def user_review(request, username):
    profile = User.objects.get(username=username)
    reviews = Review.objects.filter(user=profile)
    context = {'profile': profile, 'reviews': reviews}
    return render(request, 'user_review.html', context)


def category_view(request, pk):
    category = Category.objects.get(pk=pk)
    products = Product.objects.filter(category=category)
    context = {'category': category, 'products': products}
    return render(request, 'category.html', context)


def brand_view(request, pk):
    brand = Brand.objects.get(pk=pk)
    products = Product.objects.filter(brand=brand)
    context = {'brand': brand, 'products': products}
    return render(request, 'brand.html', context)


def search_view(request):
    query = request.GET.get('q')
    products = Product.objects.filter(Q(title__icontains=query) | Q(brand__title__icontains=query) | Q(category__title__icontains=query))
    context = {'query': query, 'products': products}
    return render(request, 'search.html', context)

cosapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">
    <title>{% block title %}cosapp{% endblock %}</title>
</head>
<body>
    <header class="mb-3 border-bottom">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">cosapp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Категории</a>
                            <ul class="dropdown-menu" style="max-height: 300px; overflow-y: auto;">
                            {% for category in categories %}
                                <li><a class="dropdown-item" href="{% url 'category' category.id %}">{{ category }}</a></li>
                            {% endfor %}
                            </ul>
                        </li>
                          
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Бренды</a>
                            <ul class="dropdown-menu" style="max-height: 300px; overflow-y: auto;">
                            {% for brand in brands %}
                                <li><a class="dropdown-item" href="{% url 'brand' brand.id %}">{{ brand }}</a></li>
                            {% endfor %}
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'product_new' %}">Добавить продукт</a>
                        </li>
                    </ul>

                    <form class="d-flex ms-auto" role="search" action="{% url 'search' %}">
                        <input class="form-control me-2" name="q" type="search" placeholder="Поиск" aria-label="Поиск">
                    </form>

                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}

                         <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{user.username}}</a>
                             <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'user_purchase' user.username %}">Мои покупки</a></li>
                                <li><a class="dropdown-item" href="{% url 'user_review' user.username %}">Мои оценки</a></li>
                             </ul>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                        </li>

                        {% else %}

                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Войти</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Создать аккаунт</a>
                        </li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    {% block content %}{% endblock %}

    <script src="{% static 'bootstrap.bundle.js' %}"></script>
</body>
</html>

cosapp/templates/brand.html
{% extends "base.html" %}
{% block title %}{{brand.title}}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <p class="h1 text-center mb-4">Бренд: {{brand.title}}</p>
        {% for product in products %}
            {% include 'product.html' with product=product %}
        {% endfor %}
    </div>
</div>
{% endblock %}

cosapp/templates/category.html
{% extends "base.html" %}
{% block title %}{{category.title}}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <p class="h1 text-center mb-4">Категория: {{category.title}}</p>
        {% for product in products %}
            {% include 'product.html' with product=product %}
        {% endfor %}
    </div>
</div>
{% endblock %}

cosapp/templates/login.html
{% extends "base.html" %}

{% block title %}Логин{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4 mx-auto">
            <h1>Логин</h1>
            {% load crispy_forms_tags %}
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Вход</button>
            </form>      
        </div>
    </div>
</div>
{% endblock %}

cosapp/templates/product.html
<div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
    <div class="card h-100 border border-light-subtle">
        <a href="{% url 'product_detail' product.id %}">
            <img src="{{ product.picture.url }}" class="card-img-top p-2" alt="" style="object-fit: contain; aspect-ratio: 1/1;">
        </a>
        <div class="card-body">
            <p class="card-subtitle mb-1"><a class="link-offset-2 link-underline link-underline-opacity-0 link-underline-opacity-25-hover text-body-secondary" href="{% url 'category' product.category.id %}">{{ product.category }}</a></p>
            <h5 class="card-title"><a href="{% url 'brand' product.brand.id %}" class="link-offset-2 link-underline link-underline-opacity-0 link-underline-opacity-25-hover text-body">{{ product.brand }}</a> {{ product.title }}</h5>
            {% with avg_rating=product.get_average_rating %}
                {% if avg_rating > 0 %}
                    <small>
                        <span>{{ product.get_hearts_display }}</span>
                        <span class="text-muted">({{ avg_rating|floatformat:1 }})</span>
                    </small>
                {% else %}
                    <small class="text-muted">Нет отзывов</small>
                {% endif %}
            {% endwith %}
            {% with min_price=product.get_minimal_price %}
                {% if min_price > 0 %}
                    <small>
                        <span class="text-muted">{{ min_price|floatformat:1 }}</span>
                    </small>
                {% endif %}
            {% endwith %}
        </div>
    </div>
</div>

cosapp/templates/product_detail.html
{% extends "base.html" %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-3 text-center">
            <img src="{{ product.picture.url }}" alt="" style="width: 100%; object-fit: contain; aspect-ratio: 1/1;">
        </div>
        <div class="col">
            <a href="{% url 'category' product.category.id %}" class="h6">{{ product.category }}</a>
            <h1>{{ product.title }}</h1>
            <a href="{% url 'brand' product.brand.id %}" class="h6 d-block">{{ product.brand }}</a>
            <div class="average-rating mb-3">
                {% with avg_rating=product.get_average_rating %}
                    {% if avg_rating > 0 %}
                        <div class="rating-hearts">
                            <span style="font-size: 1.5em;">{{ product.get_hearts_display }}</span>
                            <span class="ms-2">({{ avg_rating|floatformat:1 }})</span>
                        </div>
                    {% else %}
                        <p class="text-muted">Нет отзывов</p>
                    {% endif %}
                {% endwith %}
            </div>
            {% if user.is_authenticated %}
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#purchaseModal">
                Товар приобретен
            </button>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#reviewModal">
                Оценить товар
            </button>
            {% endif %}
            {% for review in reviews %}
            <div class="card mt-3">
                <div class="card-body">
                    <p class="card-text">{{ review.user.username }}</p>
                    <p class="card-text h5">{{ review.get_rating_display }} {{ review.liked|yesno:"👍🏼, 👎🏼, " }}</p>
                    <p class="card-text">{{ review.comment }}</p>
                </div>
            </div>
            {% endfor %}
            {% for purchase in purchases %}
            <div class="card mt-3">
                <div class="card-body">
                    <p class="card-text">{{ purchase.date }}</p>
                    <p class="card-text">{{ purchase.price }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="modal fade" id="purchaseModal" tabindex="-1" aria-labelledby="purchaseModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="purchaseModalLabel">Информация о покупке</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    {% load crispy_forms_tags %}
                    <form method="POST" action="{% url 'purchase_new' product.id %}" id="purchase">
                        {% csrf_token %}
                        {{ purchase_form|crispy }}
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary" form="purchase">Сохранить</button>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="reviewModalLabel">Оценка товара</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    {% load crispy_forms_tags %}
                    <form method="POST" action="{% url 'review_new' product.id %}" id="review">
                        {% csrf_token %}
                        {{ review_form|crispy }}
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary" form="review">Сохранить</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

cosapp/templates/product_edit.html
{% extends "base.html" %}

{% block title %}Добавление продукта{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4 mx-auto">
            <h1>Продукт</h1>
            {% load crispy_forms_tags %}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>      
        </div>
    </div>
</div>
{% endblock %}

cosapp/templates/product_list.html
{% extends "base.html" %}

{% block title %}cosapp{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% for product in page_obj %}
            {% include 'product.html' with product=product %}
        {% endfor %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="{% url 'home' %}?page={{ page_obj.previous_page_number }}">Предыдущая страница</a></li>
                {% endif %}
                {% for page_number in page_obj.paginator.page_range %}
                    {% if page_obj.number == page_number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="{% url 'home' %}?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="{% url 'home' %}?page={{ page_number }}">{{ page_number }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="{% url 'home' %}?page={{ page_obj.next_page_number }}">Следующая страница</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

cosapp/templates/search.html
{% extends "base.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <p class="h1 text-center mb-4">Поиск по запросу {{ query }}</p>
        {% for product in products %}
            {% include 'product.html' with product=product %}
        {% endfor %}
    </div>
</div>
{% endblock %}

cosapp/templates/signup.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4 mx-auto">
            <h1>Регистрация</h1>
            {% load crispy_forms_tags %}
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Регистрация</button>
            </form>      
        </div>
    </div>
</div>
{% endblock %}

cosapp/templates/user_purchase.html
{% extends "base.html" %}

{% block title %}{{profile.username}} - Покупки{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <p class="h1 text-center mb-4">{{profile.username}}</p>
        <ul class="nav nav-pills mb-4">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'user_purchase' profile.username %}">Покупки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_review' profile.username %}">Оценки</a>
          </li>
        </ul>
        <table class="table">
            <tbody>
            {% for purchase in purchases %}
            <tr>
                <td>
                    <a href="{% url 'product_detail' purchase.product.id %}">
                        <img src="{{ purchase.product.picture.url }}" alt=""
                             style="width: 75px; object-fit: contain; aspect-ratio: 1/1;"></a></td>
                <td>
                    <a href="{% url 'product_detail' purchase.product.id %}" class="h6">
                        {{ purchase.product.title }}</a><br>{{ purchase.product.category }}
                </td>
                <td>{{ purchase.product.brand }}</td>
                <td>{{ purchase.date }}</td>
                <td>{{ purchase.price }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

cosapp/templates/user_review.html
{% extends "base.html" %}

{% block title %}{{profile.username}} - Оценки{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <p class="h1 text-center mb-4">{{profile.username}}</p>
        <ul class="nav nav-pills mb-4">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_purchase' profile.username %}">Покупки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'user_review' profile.username %}">Оценки</a>
          </li>
        </ul>
        {% for review in reviews %}
        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-3">
        <div class="card h-100 border border-light-subtle">
          <div class="row g-0">
            <div class="col-md-4">
              <a href="{% url 'product_detail' review.product.id %}">
                        <img src="{{ review.product.picture.url }}" class="card-img img-fluid rounded-start p-2" alt=""
                             style="object-fit: contain; aspect-ratio: 1/1;"></a>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <p class="card-subtitle mb-1"><a class="link-offset-2 link-underline link-underline-opacity-0 link-underline-opacity-25-hover text-body-secondary" href="{% url 'category' review.product.category.id %}">{{ review.product.category }}</a></p>
                <h5 class="card-title"><a class="link-offset-2 link-underline link-underline-opacity-0 link-underline-opacity-25-hover text-body" href="{% url 'brand' review.product.brand.id %}">{{ review.product.brand }}</a> {{ review.product.title }}</h5>
                <p class="card-text"><small>{{ review.get_rating_display }} {{ review.liked|yesno:"👍🏼, 👎🏼, " }}</small></p>
                <p class="card-text">{{ review.comment }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
        {% endfor %}
    </div>
</div>
{% endblock %}